# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
# Copyright 2022 Observational Health Data Sciences and Informatics
#
# This file is part of DbProfileModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create specifications for the DbDiagnosticsModule
#'
#' @param dataDiagnosticsSettings		A list of settings created from DataDiagnostics::createDataDiagnosticsSettings() function
#'                    
#'
#' @return
#' An object of type `DbDiagnosticsModuleSpecifications`.
#'
#' @export
createDbDiagnosticsModuleSpecifications <- function(dataDiagnosticsSettings) {
  analysis <- list()
  for (name in names(formals(createDbDiagnosticsModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }
  
  specifications <- list(module = "DbDiagnosticsModule",
                         version = "0.0.1",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("DbDiagnosticsModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
